"""empty message

Revision ID: d3b0bd72a42a
Revises: 833724243ce0
Create Date: 2024-04-08 01:34:04.729922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b0bd72a42a'
down_revision = '833724243ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battles')
    op.drop_table('monsters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imageUrl', sa.VARCHAR(), nullable=False),
    sa.Column('attack', sa.INTEGER(), nullable=False),
    sa.Column('defense', sa.INTEGER(), nullable=False),
    sa.Column('hp', sa.INTEGER(), nullable=False),
    sa.Column('speed', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('winner', sa.INTEGER(), nullable=True),
    sa.Column('monsterA', sa.INTEGER(), nullable=True),
    sa.Column('monsterB', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
